# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('members', models.TextField()),
                ('date', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=16)),
            ],
        ),
    ]
